# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    name: Build the project for windows
    runs-on: windows-latest
    
    steps:
    -  name: publish command
       run: dotnet publish Super-Tic-Tac-Toe/Super-Tic-Tac-Toe.csproj
