# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    name: Build the project for windows
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: publish windows
      run: dotnet publish -r win-x64
    - name: create release
      run: gh release create D:/a/Super-Tic-Tac-Toe/Super-Tic-Tac-Toe/Super-Tic-Tac-Toe/bin/Release/net8.0-windows/win-x64/publish/Super-Tic-Tac-Toe.exe   --title 'latest release' --notes 'this is the latest release' --latest
      env:
        GH_TOKEN: ${{ github.token }}
